//! Emit the deliverable.
//!
//! Write `launch.argv` (one token per line) and print the same command to
//! stdout. With `--headless` also write a companion `launch.env` carrying the
//! software-GL hints for the caller to source - never an xvfb-wrapped command
//!. Optionally write a `resolution.lock` audit manifest.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use log::info;
use serde::Serialize;

use crate::model::artifact::{ArtifactRecord, Role};

/// A single `launch.env` entry: the variable, its value, and a one-line `note`
/// emitted as a `# comment` above it.
struct EnvHint {
    key: &'static str,
    value: &'static str,
    note: &'static str,
}

/// Software-GL and silent-audio environment hints written to `launch.env` under
/// `--headless`. The caller sources these; they are not part of the argv.
const HEADLESS_ENV: &[EnvHint] = &[
    EnvHint {
        key: "LIBGL_ALWAYS_SOFTWARE",
        value: "1",
        note: "Force Mesa software rendering (headless hosts have no GPU)",
    },
    EnvHint {
        key: "GALLIUM_DRIVER",
        value: "llvmpipe",
        note: "Render OpenGL through the llvmpipe software rasterizer",
    },
    EnvHint {
        key: "ALSOFT_DRIVERS",
        value: "null",
        note: "OpenAL Soft null backend: init audio with no sound device present",
    },
    EnvHint {
        key: "LP_NUM_THREADS",
        value: "2",
        note: "Cap llvmpipe worker threads so it doesn't oversubscribe CI cores",
    },
];

/// Contents of the headless `alsoft.conf`. `rt-prio = 0` stops OpenAL Soft from
/// requesting real-time scheduling, 
/// which it otherwise probes for `RTKit` - a D-Bus service.
const ALSOFT_CONF: &str = "\
# Generated by prism-bootstrap for --headless runs.\n\
[general]\n\
rt-prio = 0\n";

/// Write `launch.argv` to `argv_path`, print the command to stdout, and (when
/// `headless`) write `launch.env` beside it. Always writes `resolution.lock`
/// next to the argv as a cheap audit manifest.
///
/// # Errors
/// Returns an error if any output file cannot be written.
pub fn emit(
    argv: &[String],
    argv_path: &Path,
    records: &[ArtifactRecord],
    headless: bool,
    game_dir: &Path,
) -> Result<()> {
    // One token per line, trailing newline.
    let argv_text = format!("{}\n", argv.join("\n"));
    std::fs::write(argv_path, argv_text)
        .with_context(|| format!("writing launch.argv to {}", argv_path.display()))?;
    info!("Wrote launch command ({} tokens) to {}", argv.len(), argv_path.display());

    // The deliverable also goes to stdout as a single runnable line.
    println!("{}", argv.join(" "));

    let output_dir = argv_path.parent().unwrap_or_else(|| Path::new("."));

    if headless {
        write_headless_config(output_dir, game_dir)?;
    }
    write_resolution_lock(&output_dir.join("resolution.lock"), records)?;
    Ok(())
}

/// Write the headless config bundle: an `alsoft.conf` (see [`ALSOFT_CONF`]) and
/// the `launch.env` that points at it, both beside the argv.
fn write_headless_config(output_dir: &Path, game_dir: &Path) -> Result<()> {
    let alsoft_conf = write_alsoft_conf(output_dir)?;
    // `ALSOFT_CONF` is resolved against the game's cwd at launch (the game dir),
    // so reference the conf relative to that - this keeps the instance portable
    // (no build-machine paths baked in). Fall back to the absolute path only if
    // the two share no common root (e.g. different drives on Windows).
    let conf_ref = relative_path(game_dir, &alsoft_conf).unwrap_or(alsoft_conf);
    write_env(&output_dir.join("launch.env"), &conf_ref)?;
    Ok(())
}

/// Write `alsoft.conf` and return its absolute path (the relative reference for
/// `launch.env` is derived from this by [`write_headless_config`]).
fn write_alsoft_conf(output_dir: &Path) -> Result<PathBuf> {
    let conf_path = output_dir.join("alsoft.conf");
    std::fs::write(&conf_path, ALSOFT_CONF)
        .with_context(|| format!("writing alsoft.conf to {}", conf_path.display()))?;
    // Fall back to the joined path if absolutising fails (e.g. cwd unreadable).
    let absolute = std::path::absolute(&conf_path).unwrap_or(conf_path);
    info!(" - wrote headless audio config to {}", absolute.display());
    Ok(absolute)
}

/// Express `to` relative to the directory `from` (both absolutised first), e.g.
/// `<inst>/.minecraft` + `<inst>/alsoft.conf` -> `../alsoft.conf`. Returns `None`
/// when they share no common root, since no `..` chain can bridge that.
fn relative_path(from: &Path, to: &Path) -> Option<PathBuf> {
    let from = std::path::absolute(from).ok()?;
    let to = std::path::absolute(to).ok()?;
    let mut from_components = from.components().peekable();
    let mut to_components = to.components().peekable();

    // Walk off the shared prefix; count it so we can reject disjoint roots.
    let mut shared = 0;
    while let (Some(left), Some(right)) = (from_components.peek(), to_components.peek()) {
        if left != right {
            break;
        }
        from_components.next();
        to_components.next();
        shared += 1;
    }
    if shared == 0 {
        return None;
    }

    // One `..` for each remaining `from` segment, then the rest of `to`.
    let mut relative = PathBuf::new();
    for _ in from_components {
        relative.push("..");
    }
    relative.extend(to_components);
    Some(relative)
}

/// Write the headless `launch.env`: each variable preceded by a `# note`, then
/// the dynamic `ALSOFT_CONF` pointing at `alsoft_conf`.
fn write_env(env_path: &Path, alsoft_conf: &Path) -> Result<()> {
    let mut text = String::new();
    for hint in HEADLESS_ENV {
        push_env_line(&mut text, hint.note, hint.key, hint.value);
    }
    // ALSOFT_CONF carries a runtime path, so it's emitted here rather than in
    // the static HEADLESS_ENV table above.
    push_env_line(
        &mut text,
        "Point OpenAL Soft at the generated config (disables its RTKit probe)",
        "ALSOFT_CONF",
        &alsoft_conf.to_string_lossy(),
    );
    std::fs::write(env_path, text)
        .with_context(|| format!("writing launch.env to {}", env_path.display()))?;
    info!(" - wrote headless env hints to {}", env_path.display());
    Ok(())
}

/// Append a `# note` comment line followed by `key=value` to `text`.
fn push_env_line(text: &mut String, note: &str, key: &str, value: &str) {
    text.push_str("# ");
    text.push_str(note);
    text.push('\n');
    text.push_str(key);
    text.push('=');
    text.push_str(value);
    text.push('\n');
}

/// A single artifact row in `resolution.lock`.
#[derive(Serialize)]
struct LockEntry<'a> {
    coordinate: &'a str,
    url: Option<&'a str>,
    sha1: Option<&'a str>,
    local_path: String,
    role: &'static str,
}

/// Write the `resolution.lock` audit manifest: every resolved artifact's
/// coordinate, url, sha1, local path, and role.
fn write_resolution_lock(lock_path: &Path, records: &[ArtifactRecord]) -> Result<()> {
    let entries: Vec<LockEntry> = records
        .iter()
        .map(|record| LockEntry {
            coordinate: &record.coordinate,
            url: record.url.as_deref(),
            sha1: record.sha1.as_deref(),
            local_path: record.local_path.to_string_lossy().into_owned(),
            role: role_name(record.role),
        })
        .collect();
    let json = serde_json::to_string_pretty(&entries).context("serialising resolution.lock")?;
    std::fs::write(lock_path, json)
        .with_context(|| format!("writing resolution.lock to {}", lock_path.display()))?;
    Ok(())
}

/// The stable string name of a role for the manifest.
fn role_name(role: Role) -> &'static str {
    match role {
        Role::Classpath => "classpath",
        Role::MavenFile => "maven-file",
        Role::NativeExtract => "native-extract",
        Role::Asset => "asset",
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;

    fn record(coordinate: &str) -> ArtifactRecord {
        ArtifactRecord {
            coordinate: coordinate.to_owned(),
            url: Some("https://example/lib.jar".to_owned()),
            sha1: Some("abc".to_owned()),
            size: Some(1),
            local_path: PathBuf::from("/inst/libraries/lib.jar"),
            role: Role::Classpath,
            extract_exclude: Vec::new(),
        }
    }

    #[test]
    fn emit_writes_argv_one_token_per_line() {
        let dir = std::env::temp_dir().join(format!("mc-emit-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let argv_path = dir.join("launch.argv");
        let argv = vec!["/jdk/bin/java".to_owned(), "-Xmx1g".to_owned(), "Main".to_owned()];

        emit(&argv, &argv_path, &[record("g:a:1")], false, &dir.join(".minecraft")).unwrap();

        let written = std::fs::read_to_string(&argv_path).unwrap();
        assert_eq!(written, "/jdk/bin/java\n-Xmx1g\nMain\n");
        // resolution.lock written beside it; launch.env not (not headless).
        assert!(dir.join("resolution.lock").exists());
        assert!(!dir.join("launch.env").exists());

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn headless_writes_env_file() {
        let dir = std::env::temp_dir().join(format!("mc-emit-env-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let argv_path = dir.join("launch.argv");

        // Default game dir sits one level under the output dir, like a real run.
        emit(&["java".to_owned()], &argv_path, &[], true, &dir.join(".minecraft")).unwrap();

        let env = std::fs::read_to_string(dir.join("launch.env")).unwrap();
        assert!(env.contains("LIBGL_ALWAYS_SOFTWARE=1"));
        assert!(env.contains("GALLIUM_DRIVER=llvmpipe"));
        assert!(env.contains("LP_NUM_THREADS=2"));
        assert!(env.contains("ALSOFT_DRIVERS=null"));
        // ALSOFT_CONF references the conf relative to the game dir (its cwd).
        assert!(env.contains("ALSOFT_CONF=../alsoft.conf"));
        let conf = std::fs::read_to_string(dir.join("alsoft.conf")).unwrap();
        assert!(conf.contains("rt-prio = 0"));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn relative_path_walks_up_to_shared_root() {
        // Game dir one level under the conf's dir -> single `..`.
        assert_eq!(
            relative_path(Path::new("/inst/.minecraft"), Path::new("/inst/alsoft.conf")),
            Some(PathBuf::from("../alsoft.conf"))
        );
        // Deeper game dir -> one `..` per extra level.
        assert_eq!(
            relative_path(Path::new("/inst/a/b"), Path::new("/inst/alsoft.conf")),
            Some(PathBuf::from("../../alsoft.conf"))
        );
        // Conf already in the game dir -> bare filename.
        assert_eq!(
            relative_path(Path::new("/inst"), Path::new("/inst/alsoft.conf")),
            Some(PathBuf::from("alsoft.conf"))
        );
    }
}
